### ISSUE TITLE
spi receiver side has a bug maybe

### ISSUE THREAD

**Issue by mwsoli** [pulp-platform/axi_spi_master#4]
From the spi receiver side when the quad mode is disabled, the data is taken from sdi1 instead of sdi0.
This is in line number 84 in the spi_master_rx module
Is there a reason for that?

**Comment by jahagirdar** [comment]
@MohamedWHassan Why was this closed? the spi_slave uses sdi0 and master uses sdi1, and without a clear documentation that can lead to integration bug :(

**Comment by mwsoli** [comment]
As far as I understood, if you look at the SPI modes you will find that there is **std, quad_tx and quad_rx**. This means that the standard mode needs two pins working at the same time. one for transmitting and one for receiving in our case the sdo0 would be output and sdi1 would be input.

**Comment by jahagirdar** [comment]
I agree, If I am not mistaken, on the slave side they are using sdi0 and sdo0
